name:                megaparsec-learning
version:             0.1.0.0
github:              "milman2/megaparsec-learning"
license:             BSD-3-Clause
author:              "milman2"
maintainer:          "milman2@voyagergames.gg"
copyright:           "2025"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/milman2/megaparsec-learning#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.6
- text >= 2.0
- parser-combinators >= 1.3.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  megaparsec-learning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec-learning

tests:
  megaparsec-learning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec-learning
